### ISSUE TITLE
Can u use it for discord.py bot?

### ISSUE THREAD

**Issue by Kacktide** [julianYaman/discord-bot-dashboard#116]
Hey, I have a discord bot hosted on discord.py and I wanted a dashboard. First-of-all can you even make a dashboard for Discord.py? And do your dashboard support discord.py? If this was dumb sorry.

**Comment by somerandomcloud** [comment]
Hey! You could make a dashboard for discord.py, but this isnt what you would use. I have no idea how to use discord.py, but I would assume that there isnt a public dashboard available at the moment, sorry! This is for discord.js, so no this doesnt support discord.py

**Comment by julianYaman** [comment]
Hello, like @somerandomcloud already wrote, this dashboard does not support discord.py.

Sure, it would be great to also have a dashboard for bots running on discord.py but currently this dashboard does not work at the moment and there is much to be done.
