### ISSUE TITLE
How do I download this?

### ISSUE THREAD

**Issue by YouthGamer** [julianYaman/discord-bot-dashboard#4]
How do I get this working?

**Comment by julianYaman** [comment]
1. Fork it.
2. Download your fork on your local machine.
3. Run ``npm install`` in your command line interface.
4. Run ``npm start`` to start the dashbaord server (localhost:3000 on default)
5. Create a file named **private_config.json**.
6. Create in this file a new JSON object with the **token** key and with your bot token as the value (look at the README.md file (please))

**Comment by YouthGamer** [comment]
I can't go to localhost:3000

**Comment by julianYaman** [comment]
Actually yes you can, is there any error when you start the project. Normally, in the ``config.json`` there is a key name ``LISTENING_PORT`` which has the default value **3000**.

**Comment by julianYaman** [comment]
@YouthGamer Is your issue now solved or do you have any questions? 😃

**Comment by YouthGamer** [comment]
https://i.imgur.com/22MagJS.png

It is not loading the page :(
