### ISSUE TITLE
botData.json keeps getting cleared

### ISSUE THREAD

**Issue by Puyodead1** [julianYaman/discord-bot-dashboard#40]
as title says, crashes the bot and gives Unexpected end of JSON input error, just a heads up.

**Comment by Puyodead1** [comment]
same thing with log, it will eventually fk something up

**Comment by julianYaman** [comment]
I will look into this issue when I got the time. Please write if you may already found the solution sooner than me.

**Comment by julianYaman** [comment]
The issue is not valid anymore since the dashboard gets recoded.
