### ISSUE TITLE
Can't add command

### ISSUE THREAD

**Issue by YouthGamer** [julianYaman/discord-bot-dashboard#5]
Hello,

When I try to add a command it redirects me to: localhost:3000/addCommand

It gives me a 404 Error

**Comment by YouthGamer** [comment]
Adding on to my problems, I can't change my bot status with the dashboard. When I restart my bot it gives me an error. Also it doesn't show the status I put on the dashboard.

**Comment by YouthGamer** [comment]
Oh sure! 

I would love to help! I am not the best at coding, but I think I could help you with some stuff!

**Comment by YouthGamer** [comment]
I got bored of the home page so I made my own! 

https://i.imgur.com/MHHOjij.png

**Comment by julianYaman** [comment]
Did you made this?

**Comment by YouthGamer** [comment]
Yep!

**Comment by YouthGamer** [comment]
I got like the style from Mee6.xyz

But I made the rest!

**Comment by julianYaman** [comment]
Great dude, don´t forget to commit your changes on your GitHub profile and make a pull request when you think you are finished with some front-end stuff. When you´ve made the frontend stuff, create the request and I can merge your changes to this repository.

**Comment by julianYaman** [comment]
@YouthGamer, but I don´t think "Fiber" is the name of this project. Replace it with Bot Dashboard until I have a good name.

**Comment by YouthGamer** [comment]
Actually, Fiber is my bot. As I said before I made my own dashboard for my bot. I could make another version deleting the Fiber and putting the 'Bot Dashboard'.

**Comment by julianYaman** [comment]
@YouthGamer, you could use this design (in a slightly changed version) and replace the title of the project and then you could commit that frontend change to your repo and then make a pull request with the frontend changes to this repo.

**Comment by julianYaman** [comment]
Sure! I‘ll make a „Contributors“ section to the README where I‘m going to list everyone who helped already.

And in the package.json, there is already a object for contributors. 

Maybe we could add an external Contributors page in the Dashboard.

**Comment by YouthGamer** [comment]
I think that is great! What is your discord?

**Comment by YouthGamer** [comment]
Add me on discord: LucasGamer213#6451

**Comment by julianYaman** [comment]
@YouthGamer Cannot add you. Add me (yaman#8901) and join my discord: https://discord.me/yaman

**Comment by darealHeroBrine** [comment]
When i put my bot in maintanence it wont run anymore and i have to reinstall the whole rthing and add changing the status of the game or status breaks it too.

**Comment by julianYaman** [comment]
@darealHeroBrine Oh, this is very strange. Maybe you can check the maintenance function in this project if something is not ok in there.
