### ISSUE TITLE
Supporting multiple languages

### ISSUE THREAD

**Issue by julianYaman** [julianYaman/discord-bot-dashboard#92]
**Is your feature request related to a problem? Please describe.**
Currently, the dashboard is only available in English.
Despite of most code is written in English and uses this language, it would make life much easier for bot developers if they can use the dashboard in their mother tongue.

It could be done with language config files where any description and word in the dashboard is translated in its config file.

It would be the easiest approach to begin with:
- English 
- German 

and continuing with

- French 
- Russian
- Spanish
- Italian

**Comment by HysMX** [comment]
If this is still a thing i can translate into ES_mx

**Comment by X-Niter** [comment]
Other then life keeping us busy, it is very much a thing and I'm sure that once it comes around to it we will most definitely be reaching out to translators.
